C MODPATH-PLOT Version 3.00 (V3, Release 2, 6-2000)
C Changes:
C   No change since previous release: (V3, Release 1, 9-94)
C***** SUBROUTINES *****
C     DCFDRW
C***********************
 
C***** SUBROUTINE *****
      SUBROUTINE DCFDRW(IOPT,IU,MAXCLR,NT1,NT2,LVSACT,MAXLVS,I7)
      CHARACTER*1 COM
      CHARACTER*10 CH
      CHARACTER*80 STRING,LINE
      DIMENSION X(200),Y(200),TXEXTX(5),TXEXTY(5)
      DIMENSION LVSACT(MAXLVS)
C
      COM= '@'
C
      IF(IOPT.EQ.1) THEN
      DO 1 N=1,MAXLVS
1     LVSACT(N)=0
      ELSE
      IF(LVSACT(IOPT).EQ.0) RETURN
      END IF
      CALL FINDUN(IUOUT)
      OPEN(IUOUT,STATUS='SCRATCH')
      CALL GSFAIS(1)
      CALL GSELTR(NT2)
      RPD= 3.14159/180.0
      MAXLIN=200
C--- SAVE PARAMETER VALUES SO THEY CAN BE RESET LATER
      CALL GQPLCI(IERR,ILCOLD)
      CALL GQLN(IERR,LSOLD)
      CALL GQTXAL(IERR,IHOLD,IVOLD)
      CALL GQTXCI(IERR,ITCOLD)
      CALL GQMK(IERR,IMOLD)
      CALL GQPMCI(IERR,IMCOLD)
      CALL GQMKSC(IERR,SCMOLD)
      CALL GQCHH(IERR,HEIGHT)
      CALL GQFAIS(IERR,IFSOLD)
      CALL GQFACI(IERR,IFCOLD)
      CALL GQCHUP(IERR,CHUX,CHUY)
      CALL QFADN(IFD1,IFD2)
      CALL QFAST(IFSOLD)
C SET FILL STYLE TO TYPE 1 (+45 DIAGONALS)
      CALL SFAST(1)
C SET FILL COLOR INDEX TO 1
      CALL GSFACI(1)
C SET MARKER COLOR INDEX TO 1
      CALL GSPMCI(1)
C SET LINE COLOR INDEX TO 1
      CALL GSPLCI(1)
C SET TEXT COLOR INDEX TO 1
      CALL GSTXCI(1)
C SET LINE STYLE TO 1 (SOLID)
      CALL GSLN(1)
C SET TEXT ALIGNMENT TO BOTTOM LEFT
      CALL GSTXAL(1,5)
C SET MARKER TYPE TO 3 (ASTERISK)
      CALL GSMK(3)
C SET MARKER SCALE FACTOR TO 1.0
      CALL GSMKSC(1.0)
C SET TEXT FILL FLAG TO -1 (NO FILL)
      ITFILL= -1
C
      REWIND(IU)
C
10    READ(IU,'(A)',END=100) LINE
      IF(LINE(1:1).EQ.COM) GO TO 10
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,1,NDUMMY,RDUMMY,I7,IU)
      CH= LINE(IWSTRT:IWLAST)
C
C------------------- draw/fill polygon -----------------------------
      IF(CH.EQ.'PL.BEGIN') THEN
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ILAYER,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITRAN,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFILL,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ICLOSE,RDUMMY,I7,IU)
      LINDRW=1
      IF(ILAYER.GT.MAXLVS) ILAYER=0
      IF(ILAYER.GT.0) LVSACT(ILAYER)=1
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0) THEN
         CALL CHOP(LINE,LNG)
         WRITE(IUOUT,'(A)') LINE(1:LNG)
      END IF
      IF(IFILL.LT.0) THEN
      IFILL= -IFILL
      LINDRW=0
      END IF
      IF(IFILL.GT.0) ICLOSE=1
      NLINE=0
      KOUNT=0
11    READ(IU,'(A)',END=100) LINE
      IF(LINE(1:1).EQ.COM) GO TO 11
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,1,NDUMMY,RDUMMY,I7,IU)
      CH= LINE(IWSTRT:IWLAST)
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0) THEN
         CALL CHOP(LINE,LNG)
         WRITE(IUOUT,'(A)') LINE(1:LNG)
      END IF
C
      IF(CH.EQ.'PL.END') THEN
      IF(KOUNT.GT.NLINE) IFILL=0
      IF(ICLOSE.EQ.1) THEN
      NLINE=NLINE+1
      X(NLINE)=XFIRST
      Y(NLINE)=YFIRST
      END IF
      IF(KOUNT.LE.1) GO TO 10
      IF(ILAYER.EQ.IOPT) THEN
      IF(ITRAN.EQ.0) CALL GSELTR(NT1)
      IF(IFILL.EQ.2) THEN
      CALL GQFACI(IERR,ITEMP)
      CALL GSFACI(0)
      CALL QFAST(ISTOLD)
      CALL SFAST(1)
      CALL PLOTFA(NLINE,X,Y)
      CALL SFAST(ISTOLD)
      CALL GSFACI(ITEMP)
      END IF
      IF(IFILL.GT.0) CALL PLOTFA(NLINE,X,Y)
      IF(LINDRW.EQ.1) CALL PLOTPL(NLINE,X,Y)
      IF(ITRAN.EQ.0) CALL GSELTR(NT2)
      END IF
      GO TO 10
      END IF
C
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,XP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,YP,I7,IU)
      NLINE=NLINE+1
      KOUNT=KOUNT+1
      X(NLINE)=XP
      Y(NLINE)=YP
C
      IF(KOUNT.EQ.1) THEN
      XFIRST=XP
      YFIRST=YP
      END IF
C
      IF(NLINE.EQ.MAXLIN) THEN
      IF(ILAYER.EQ.IOPT) THEN
      IF(ITRAN.EQ.0) CALL GSELTR(NT1)
      IF(LINDRW.EQ.1) CALL PLOTPL(NLINE,X,Y)
      IF(ITRAN.EQ.0) CALL GSELTR(NT2)
      END IF
      NLINE=1
      X(1)=XP
      Y(1)=YP
      END IF
C
      GO TO 11
C
C-------------------- draw polymarkers -----------------------------
      ELSE IF(CH.EQ.'MK.BEGIN') THEN
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ILAYER,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITRAN,RDUMMY,I7,IU)
      NLINE=0
      IF(ILAYER.GT.MAXLVS) ILAYER=0
      IF(ILAYER.GT.0) LVSACT(ILAYER)=1
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0) THEN
         CALL CHOP(LINE,LNG)
         WRITE(IUOUT,'(A)') LINE(1:LNG)
      END IF
12    READ(IU,'(A)',END=100) LINE
      IF(LINE(1:1).EQ.COM) GO TO 12
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,1,NDUMMY,RDUMMY,I7,IU)
      CH= LINE(IWSTRT:IWLAST)
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0) THEN
         CALL CHOP(LINE,LNG)
         WRITE(IUOUT,'(A)') LINE(1:LNG)
      END IF
C
      IF(CH.EQ.'MK.END') THEN
      IF(NLINE.GT.0.AND.ILAYER.EQ.IOPT) CALL PLOTMK(NLINE,X,Y)
      GO TO 10
      END IF
C
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,XP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,YP,I7,IU)
      NLINE=NLINE+1
      X(NLINE)=XP
      Y(NLINE)=YP
C
      IF(NLINE.EQ.MAXLIN) THEN
      IF(ILAYER.EQ.IOPT) THEN
      IF(ITRAN.EQ.0) CALL GSELTR(NT1)
      CALL PLOTMK(NLINE,X,Y)
      IF(ITRAN.EQ.0) CALL GSELTR(NT2)
      END IF
      NLINE=0
      END IF
      GO TO 12
C
C---------------------- draw single marker ------------------------
      ELSE IF(CH.EQ.'MK') THEN
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,XP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,YP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ILAYER,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITRAN,RDUMMY,I7,IU)
      IF(ILAYER.GT.MAXLVS) ILAYER=0
      IF(ILAYER.GT.0) LVSACT(ILAYER)=1
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0)
     1   WRITE(IUOUT,'(A)') LINE
      IF(ILAYER.NE.IOPT) GO TO 10
      IF(ITRAN.EQ.0) CALL GSELTR(NT1)
      CALL PLOTMK(1,XP,YP)
      IF(ITRAN.EQ.0) CALL GSELTR(NT2)
C
C------------------------- write text -----------------------------
      ELSE IF(CH.EQ.'TX') THEN
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,XP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,YP,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ILAYER,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITRAN,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,ANGLE,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFTR,RDUMMY,I7,IU)
      IF(ILAYER.GT.MAXLVS) ILAYER=0
      IF(ILAYER.GT.0) LVSACT(ILAYER)=1
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0) THEN
         CALL CHOP(LINE,LNG)
         WRITE(IUOUT,'(A)') LINE(1:LNG)
      END IF
      READ(IU,'(A)',END=100) STRING
      CALL CHOP(STRING,LSTR)
      IF(ILAYER.NE.IOPT.AND.ILAYER.NE.0)
     1   WRITE(IUOUT,'(A)') STRING(1:LSTR)
      IF(ILAYER.NE.IOPT) GO TO 10
      ANGLE= RPD*ANGLE
      UPY= COS(ANGLE)
      UPX= -SIN(ANGLE)
      CALL GSCHUP(UPX,UPY)
      IF(ITRAN.EQ.0) CALL GSELTR(NT1)
      IF(LSTR.GT.0) THEN
        IF(IFTR.GT.0.AND.ITFILL.GE.0) THEN
        CALL GQTXX(1,XP,YP,STRING(1:LSTR),IERR,XCAT,YCAT,TXEXTX,TXEXTY)
        TXEXTX(5)=TXEXTX(1)
        TXEXTY(5)=TXEXTY(1)
        CALL GQFACI(IERR,ITEMP)
        CALL GSFACI(ITFILL)
        CALL GFA(5,TXEXTX,TXEXTY)
        CALL GSFACI(ITEMP)
        END IF
      CALL GTX(XP,YP,STRING(1:LSTR))
      END IF
      IF(ITRAN.EQ.0) CALL GSELTR(NT2)
C
C--------------------- set polyline attributes ------------------------
      ELSE IF(CH.EQ.'PL.STYLE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ISTYLE,RDUMMY,I7,IU)
      IF(ISTYLE.LT.0.OR.ISTYLE.GT.4) ISTYLE=1
      CALL GSLN(ISTYLE)
 
      ELSE IF(CH.EQ.'PL.COLOR') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ICOLOR,RDUMMY,I7,IU)
      IF(ICOLOR.LT.0.AND.ICOLOR.GT.MAXCLR) THEN
        CALL GSPLCI(1)
      ELSE
        CALL GSPLCI(ICOLOR)
      END IF
C
C------------------ set polygon fill attributes -----------------------
      ELSE IF(CH.EQ.'PF.COLOR') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFCLR,RDUMMY,I7,IU)
      IF(IFCLR.GE.0.AND.IFCLR.LE.MAXCLR) THEN
        CALL GSFACI(IFCLR)
      ELSE
        CALL GSFACI(1)
      END IF
 
      ELSE IF(CH.EQ.'PF.STYLE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFAS,RDUMMY,I7,IU)
      CALL SFAST(IFAS)
 
      ELSE IF(CH.EQ.'PF.DENSE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,FDSCAL,I7,IU)
      IF(FDSCAL.EQ.1.0) THEN
      CALL SFADN(IFD1,IFD2)
      ELSE
      F1= FLOAT(IFD1)*FDSCAL
      F2= FLOAT(IFD2)*FDSCAL
      IF1= IFIX(F1)
      IF2= IFIX(F2)
      CALL SFADN(IF1,IF2)
      END IF
C
C--------------------- set text attributes -----------------------------
      ELSE IF(CH.EQ.'TX.COLOR') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ICOLOR,RDUMMY,I7,IU)
      IF(ICOLOR.LT.0.AND.ICOLOR.GT.MAXCLR) THEN
        CALL GSTXCI(1)
      ELSE
        CALL GSTXCI(ICOLOR)
      END IF
 
      ELSE IF(CH.EQ.'TX.ALIGN') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IH,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,II,RDUMMY,I7,IU)
      IF(IH.LT.1.OR.IH.GT.3) IH=1
      IF(II.EQ.1) IV=5
      IF(II.EQ.2) IV=3
      IF(II.EQ.3) IV=1
      CALL GSTXAL(IH,IV)
 
      ELSE IF(CH.EQ.'TX.SIZE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,TXSF,I7,IU)
      HGT= HEIGHT*TXSF
      CALL GSCHH(HGT)
 
      ELSE IF(CH.EQ.'TX.FILL') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IANS,RDUMMY,I7,IU)
      IF(IANS.GT.MAXCLR) THEN
        ITFILL=1
      ELSE IF(IANS.LT.0) THEN
        ITFILL=0
      ELSE
        ITFILL=IANS
      END IF
C
C---------------------- set marker attributes ---------------------------
      ELSE IF(CH.EQ.'MK.COLOR') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ICOLOR,RDUMMY,I7,IU)
      IF(ICOLOR.LT.0.AND.ICOLOR.GT.MAXCLR) THEN
        CALL GSPMCI(1)
      ELSE
        CALL GSPMCI(ICOLOR)
      END IF
 
      ELSE IF(CH.EQ.'MK.SIZE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,SMCF,I7,IU)
      CALL GSMKSC(SMCF)
 
      ELSE IF(CH.EQ.'MK.TYPE') THEN
      CALL CHOP(LINE,LNG)
      WRITE(IUOUT,'(A)') LINE(1:LNG)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IMTYPE,RDUMMY,I7,IU)
      IF(IMTYPE.GE.1.AND.IMTYPE.LE.5) CALL GSMK(IMTYPE)
      END IF
 
      GO TO 10
 
100   CONTINUE
C
C--- RESET PARAMETERS TO THE VALUES THEY HAD ORIGINALLY
      CALL GSELTR(NT1)
      CALL GSPMCI(IMCOLD)
      CALL GSPLCI(ILCOLD)
      CALL GSTXCI(ITCOLD)
      CALL GSLN(LSOLD)
      CALL GSTXAL(IHOLD,IVOLD)
      CALL GSMK(IMOLD)
      CALL GSMKSC(SCMOLD)
      CALL GSCHH(HEIGHT)
      CALL GSFACI(IFCOLD)
      CALL GSCHUP(CHUX,CHUY)
      CALL SFADN(IFD1,IFD2)
      CALL SFAST(IFSOLD)
      CLOSE(IU)
      IU=IUOUT
      RETURN
      END
