C MODPATH-PLOT Version 3.00 (V3, Release 2, 6-2000)
C Changes:
C   No change since previous release: (V3, Release 1, 9-94)
C***** SUBROUTINES *****
C     QWSIZE
C     BEFORE
C     AFTER
C     RWSIZE
C     SWSIZE
C***********************
 
C***** SUBROUTINE *****
      SUBROUTINE QWSIZE(IWK,IERR,IDCUN,RXM,RYM,NPIXX,NPIXY)
      CALL GQWKC(IWK,IERR,ICID,IWSTYP)
      CALL GQDSP(IWSTYP,IERR,IDCUN,RXM,RYM,NPIXX,NPIXY)
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE BEFORE(MODEL,VER,RXMDEV,RYMDEV,NPXDEV,NPYDEV)
      CHARACTER*(*) VER
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE AFTER(MODEL,VER,RXMDEV,RYMDEV,NPXDEV,NPYDEV)
      CHARACTER*(*) VER
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE RWSIZE(IOPT,LXLAST,LYLAST,ICODE)
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE SWSIZE(VER)
      RETURN
      END
