C MODPATH-PLOT Version 3.00 (V3, Release 2, 6-2000)
C Changes:
C   No change since previous release: (V3, Release 1, 9-94)
C***** SUBROUTINES *****
C     PWELLS
C     SYMBL
C     PRIVER
C     PDRAIN
C     PGHB
C     SPTR1
C     PSTRM
C     SPTR2
C***********************
 
C***** SUBROUTINE *****
      SUBROUTINE PWELLS (IMIN,IMAX,JMIN,JMAX,KMIN,KMAX,XMN,XMX,
     1YMN,YMX,ZXT,ZXB,NCOL,NROW,NLAY,IVIEW,IUWELL,NCLR,I7,IPROJ,ISLICE,
     2KPER,NDIM1,NDIM2,IXYDIR)
      COMMON /COLORS/
     1 ICO(20),ICYCL(20),CTR(0:255),CTG(0:255),CTB(0:255),NCYCL,NCTDEF,
     2 MCI
      DIMENSION XMN(NCOL),XMX(NCOL),YMN(NROW),YMX(NROW),
     1ZXT(NDIM1,NDIM2),ZXB(NDIM1,NDIM2)
      DIMENSION XP(7),YP(7)
      CHARACTER*81 LINE
C
      IV= IVIEW*IPROJ
      IF(NCLR.GE.0) THEN
      CALL PKCLR (ICO(8) )
      END IF
      WRITE(I7,5000)
5000  FORMAT(' ---------------------------------------------------------
     1----------------------')
      WRITE(I7,*) 'WELL DATA BEING READ...'
      CALL SPTR1(IUWELL,I7,KPER)
      READ(IUWELL,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NWELL,RDUMMY,I7,IUWELL)
      IF(NWELL.GT.0) THEN
      DO 10 N=1,NWELL
      READ(IUWELL,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,K,RDUMMY,I7,IUWELL)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,I,RDUMMY,I7,IUWELL)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,J,RDUMMY,I7,IUWELL)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,Q,I7,IUWELL)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFACE,RDUMMY,I7,IUWELL)
      IF(IFACE.NE.0) GO TO 10
      IF(I.LT.IMIN.OR.I.GT.IMAX) GO TO 10
      IF(J.LT.JMIN.OR.J.GT.JMAX) GO TO 10
      IF(K.LT.KMIN.OR.K.GT.KMAX) GO TO 10
      IF (IV.EQ.1.AND.K.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.2.AND.J.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.3.AND.I.NE.ISLICE) GO TO 10
      IF(IVIEW.EQ.1) THEN
        X=(XMX(J)+XMN(J))/2.0
        Y=(ZXT(J,I)+ZXB(J,I))/2.0
        DX=XMX(J)-XMN(J)
        DY=ZXT(J,I)-ZXB(J,I)
        CALL SYMBL (X,Y,DX,DY,1)
      ELSE IF(IVIEW.EQ.2) THEN
        IF(IXYDIR.EQ.0) THEN
          II=NROW-I+1
        ELSE
          II=I
        END IF
        X=(YMX(II)+YMN(II))/2.0
        Y=(ZXT(II,K)+ZXB(II,K))/2.0
        CALL GETCPT(II,K,ZXT,ZXB,NROW,NLAY,YP,7)
        XP(1)=YMN(II)
        XP(2)=X
        XP(3)=YMX(II)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      ELSE IF(IVIEW.EQ.3) THEN
        IF(IXYDIR.EQ.0) THEN
          JJ=J
        ELSE
          JJ=NCOL-J+1
        END IF
        X=(XMX(JJ)+XMN(JJ))/2.0
        Y=(ZXT(JJ,K)+ZXB(JJ,K))/2.0
        CALL GETCPT(JJ,K,ZXT,ZXB,NCOL,NLAY,YP,7)
        XP(1)=XMN(JJ)
        XP(2)=X
        XP(3)=XMX(JJ)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      END IF
10    CONTINUE
      END IF
5020  FORMAT(3I10,F10.0,I10)
      WRITE(I7,*) '  WELL DATA HAS BEEN READ...'
      IF (NCLR.GE.0) CALL PKCLR (ICO(7))
      CLOSE(IUWELL)
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE SYMBL (XC,YC,DELR,DELC,ISYM)
      DIMENSION X(20),Y(20)
      DMIN=DELR
      IF(DELC.LT.DELR) DMIN=DELC
      IF(ISYM.EQ.0) THEN
      X(1)= XC-0.45*DELR
      Y(1)= YC-0.45*DELC
      X(2)= XC+0.45*DELR
      Y(2)= Y(1)
      X(3)= X(2)
      Y(3)= YC+0.45*DELC
      X(4)= X(1)
      Y(4)= Y(3)
      X(5)= X(1)
      Y(5)= Y(1)
      CALL PLOTPL(5,X,Y)
      ELSE IF(ISYM.EQ.1) THEN
      X(1)= XC-0.1625*DMIN
      Y(1)= YC-0.25*DMIN
      X(2)= XC+0.1625*DMIN
      Y(2)= Y(1)
      X(3)= XC+0.25*DMIN
      Y(3)= YC-0.1625*DMIN
      X(4)= X(3)
      Y(4)= YC+0.1625*DMIN
      X(5)= XC+0.1625*DMIN
      Y(5)= YC+0.25*DMIN
      X(6)= XC-0.1625*DMIN
      Y(6)= Y(5)
      X(7)= XC-0.25*DMIN
      Y(7)= YC+0.1625*DMIN
      X(8)= X(7)
      Y(8)= YC-0.1625*DMIN
      X(9)= X(1)
      Y(9)= Y(1)
      CALL PLOTPL(9,X,Y)
      ELSE IF(ISYM.EQ.2) THEN
      X(1)= XC-0.5*DMIN
      Y(1)= YC+0.5*DMIN
      X(2)= XC+0.5*DMIN
      Y(2)= YC-0.5*DMIN
      CALL PLOTPL(2,X,Y)
      YTEMP=Y(1)
      Y(1)=Y(2)
      Y(2)=YTEMP
      CALL PLOTPL(2,X,Y)
      ELSE IF(ISYM.EQ.3) THEN
      X1= XC-0.5*DMIN
      Y1= YC-0.433*DMIN
      X2= XC+0.5*DMIN
      Y2= Y1
      X3= XC
      Y3= YC+0.433*DMIN
      X(1)=X1
      Y(1)=Y1
      X(2)=X2
      Y(2)=Y2
      CALL PLOTPL(2,X,Y)
      X(1)=X2
      Y(1)=Y2
      X(2)=X3
      Y(2)=Y3
      CALL PLOTPL(2,X,Y)
      X(1)=X3
      Y(1)=Y3
      X(2)=X1
      Y(2)=Y1
      CALL PLOTPL(2,X,Y)
      ELSE IF (ISYM.EQ.4) THEN
      X(1)=XC
      X(2)=XC
      Y(1)=YC-0.5*DMIN
      Y(2)=YC+0.5*DMIN
      CALL PLOTPL(2,X,Y)
      X(1)=XC-0.5*DMIN
      X(2)=XC+0.5*DMIN
      Y(1)=YC
      Y(2)=YC
      CALL PLOTPL(2,X,Y)
      X(1)=XC-0.5*DMIN
      Y(1)=YC-0.5*DMIN
      X(2)=XC+0.5*DMIN
      Y(2)=Y(1)
      CALL PLOTPL(2,X,Y)
      X(1)=X(2)
      Y(2)=YC+0.5*DMIN
      CALL PLOTPL(2,X,Y)
      Y(1)=Y(2)
      X(2)=XC-0.5*DMIN
      CALL PLOTPL(2,X,Y)
      X(1)=X(2)
      Y(2)=YC-0.5*DMIN
      CALL PLOTPL(2,X,Y)
      ELSE IF (ISYM.EQ.5) THEN
      X(1)=XC
      X(2)=XC
      Y(1)=YC-0.5*DMIN
      Y(2)=YC+0.5*DMIN
      CALL PLOTPL(2,X,Y)
      X(1)=XC-0.5*DMIN
      X(2)=XC+0.5*DMIN
      Y(1)=YC
      Y(2)=YC
      CALL PLOTPL(2,X,Y)
      ELSE IF (ISYM.EQ.6) THEN
      X(1)=XC-0.5*DMIN
      X(2)=XC+0.5*DMIN
      X(3)=X(2)
      X(4)=X(1)
      X(5)=X(1)
      Y(1)=YC-0.5*DMIN
      Y(2)=Y(1)
      Y(3)=YC+0.5*DMIN
      Y(4)=Y(3)
      Y(5)=Y(1)
      CALL PLOTPL(5,X,Y)
      END IF
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE PRIVER (IMIN,IMAX,JMIN,JMAX,KMIN,KMAX,XMN,XMX,YMN,
     1 YMX,NCOL,NROW,NLAY,IURIV,NCLR,IVIEW,IBUFF,I7,KPER)
      COMMON /COLORS/
     1 ICO(20),ICYCL(20),CTR(0:255),CTG(0:255),CTB(0:255),NCYCL,NCTDEF,
     2 MCI
      DIMENSION XMN(NCOL),XMX(NCOL),YMX(NROW),YMN(NROW),
     1 IBUFF(NCOL,NROW,NLAY)
      CHARACTER*81 LINE
      CHARACTER*25 STRING
C
      IF(IVIEW.GT.1) RETURN
 
      DO 10 K=1,NLAY
      DO 10 I=1,NROW
      DO 10 J=1,NCOL
10    IBUFF(J,I,K)=0
      IF (NCLR.GE.0) THEN
      CALL PKCLR (ICO(11) )
      END IF
      WRITE(I7,5000)
5000  FORMAT(' ---------------------------------------------------------
     1----------------------')
      WRITE(I7,*) 'RIVER DATA NOW BEING READ...'
      CALL SPTR1(IURIV,I7,KPER)
      READ(IURIV,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IURIV)
      IF(ITMP.EQ.0) GO TO 30
      WRITE(I7,1000) ITMP
1000  FORMAT(1X,I6,' RIVER CELLS WILL BE PROCESSED.')
      DO 20 N=1,ITMP
      READ(IURIV,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,K,RDUMMY,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,I,RDUMMY,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,J,RDUMMY,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,H,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,C,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,RB,I7,IURIV)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFACE,RDUMMY,I7,IURIV)
      iskip=0
      IF(I.LT.IMIN.OR.I.GT.IMAX) iskip=1
      IF(J.LT.JMIN.OR.J.GT.JMAX) iskip=2
      IF(K.LT.KMIN.OR.K.GT.KMAX) iskip=3
      IF (IBUFF(J,I,K).EQ.1) iskip=4
      IF (IFACE.GT.6) iskip=5
      if(iskip.gt.0) go to 25
      IBUFF(J,I,K)=1
      II=NROW-I+1
      DX=XMX(J)-XMN(J)
      DY=YMX(II)-YMN(II)
      X= (XMX(J)+XMN(J))/2.0
      Y= (YMX(II)+YMN(II))/2.0
      CALL SYMBL (X,Y,DX,DY,0)
      STRING= '      PLOTTED RIVER REACH'
      GO TO 20
25    CONTINUE
      IF(ISKIP.GE.1 .AND. ISKIP.LE.3) THEN
        STRING= ' RIVER REACH OUTSIDE PLOT'
      ELSE IF(ISKIP.EQ.4) THEN
        STRING= '    DUPLICATE RIVER REACH'
      ELSE IF(ISKIP.EQ.5) THEN
        STRING= 'IFACE > 6 FOR RIVER REACH'
      END IF
20    WRITE(I7,1100) STRING,N,K,I,J
1100  FORMAT(1X,A,I5,' IN: LAYER, ROW, COL = ',3(1X,I4))
30    CONTINUE
      WRITE(I7,*) '  RIVER DATA HAS BEEN READ'
      IF (NCLR.GE.0) CALL PKCLR (ICO(7))
      CLOSE(IURIV)
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE PDRAIN (IMIN,IMAX,JMIN,JMAX,KMIN,KMAX,XMN,XMX,
     1YMN,YMX,ZXT,ZXB,NCOL,NROW,NLAY,IVIEW,IUDRAI,NCLR,I7,IPROJ,ISLICE,
     2KPER,NDIM1,NDIM2,IXYDIR)
      COMMON /COLORS/
     1 ICO(20),ICYCL(20),CTR(0:255),CTG(0:255),CTB(0:255),NCYCL,NCTDEF,
     2 MCI
      DIMENSION XMN(NCOL),XMX(NCOL),YMN(NROW),YMX(NROW),
     1ZXT(NDIM1,NDIM2),ZXB(NDIM1,NDIM2)
      DIMENSION XP(7),YP(7)
 
      CHARACTER*81 LINE
C
      IV= IVIEW*IPROJ
      IF(NCLR.GE.0) THEN
      CALL PKCLR (ICO(9) )
      END IF
      WRITE(I7,5000)
5000  FORMAT(' ---------------------------------------------------------
     1----------------------')
      WRITE(I7,*) 'DRAIN DATA BEING READ...'
      CALL SPTR1(IUDRAI,I7,KPER)
      READ(IUDRAI,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NDRAI,RDUMMY,I7,IUDRAI)
      IF(NDRAI.GT.0) THEN
      DO 10 N=1,NDRAI
      READ(IUDRAI,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,K,RDUMMY,I7,IUDRAI)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,I,RDUMMY,I7,IUDRAI)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,J,RDUMMY,I7,IUDRAI)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,H,I7,IUDRAI)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,C,I7,IUDRAI)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFACE,RDUMMY,I7,IUDRAI)
      IF(IFACE.NE.0) GO TO 10
      IF(I.LT.IMIN.OR.I.GT.IMAX) GO TO 10
      IF(J.LT.JMIN.OR.J.GT.JMAX) GO TO 10
      IF(K.LT.KMIN.OR.K.GT.KMAX) GO TO 10
      IF (IV.EQ.1.AND.K.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.2.AND.J.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.3.AND.I.NE.ISLICE) GO TO 10
      IF(IVIEW.EQ.1) THEN
        X=(XMX(J)+XMN(J))/2.0
        Y=(ZXT(J,I)+ZXB(J,I))/2.0
        DX=XMX(J)-XMN(J)
        DY=ZXT(J,I)-ZXB(J,I)
        CALL SYMBL (X,Y,DX,DY,1)
      ELSE IF(IVIEW.EQ.2) THEN
        IF(IXYDIR.EQ.0) THEN
          II=NROW-I+1
        ELSE
          II=I
        END IF
        X=(YMX(II)+YMN(II))/2.0
        Y=(ZXT(II,K)+ZXB(II,K))/2.0
        CALL GETCPT(II,K,ZXT,ZXB,NROW,NLAY,YP,7)
        XP(1)=YMN(II)
        XP(2)=X
        XP(3)=YMX(II)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      ELSE IF(IVIEW.EQ.3) THEN
        IF(IXYDIR.EQ.0) THEN
          JJ=J
        ELSE
          JJ=NCOL-J+1
        END IF
        X=(XMX(JJ)+XMN(JJ))/2.0
        Y=(ZXT(JJ,K)+ZXB(JJ,K))/2.0
        CALL GETCPT(JJ,K,ZXT,ZXB,NCOL,NLAY,YP,7)
        XP(1)=XMN(JJ)
        XP(2)=X
        XP(3)=XMX(JJ)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      END IF
10    CONTINUE
      END IF
5020   FORMAT(3I10,2F10.0,I10)
      WRITE(I7,*) '  DRAIN DATA HAS BEEN READ...'
      IF (NCLR.GE.0) CALL PKCLR (ICO(7))
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE PGHB (IMIN,IMAX,JMIN,JMAX,KMIN,KMAX,XMN,XMX,
     1YMN,YMX,ZXT,ZXB,NCOL,NROW,NLAY,IVIEW,IUGHB,NCLR,I7,IPROJ,ISLICE,
     2KPER,NDIM1,NDIM2,IXYDIR)
      COMMON /COLORS/
     1 ICO(20),ICYCL(20),CTR(0:255),CTG(0:255),CTB(0:255),NCYCL,NCTDEF,
     2 MCI
      DIMENSION XMN(NCOL),XMX(NCOL),YMN(NROW),YMX(NROW),
     1ZXT(NDIM1,NDIM2),ZXB(NDIM1,NDIM2)
      DIMENSION XP(7),YP(7)
      CHARACTER*81 LINE
C
      IV= IVIEW*IPROJ
      IF(NCLR.GE.0) THEN
      CALL PKCLR (ICO(10) )
      END IF
      WRITE(I7,5000)
5000  FORMAT(' ---------------------------------------------------------
     1----------------------')
      WRITE(I7,*) 'GHB DATA BEING READ...'
      CALL SPTR1(IUGHB,I7,KPER)
      READ(IUGHB,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NGHB,RDUMMY,I7,IUGHB)
      IF(NGHB.GT.0) THEN
      DO 10 N=1,NGHB
      READ(IUGHB,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,K,RDUMMY,I7,IUGHB)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,I,RDUMMY,I7,IUGHB)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,J,RDUMMY,I7,IUGHB)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,H,I7,IUGHB)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,C,I7,IUGHB)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFACE,RDUMMY,I7,IUGHB)
      IF(IFACE.NE.0) GO TO 10
      IF(I.LT.IMIN.OR.I.GT.IMAX) GO TO 10
      IF(J.LT.JMIN.OR.J.GT.JMAX) GO TO 10
      IF(K.LT.KMIN.OR.K.GT.KMAX) GO TO 10
      IF (IV.EQ.1.AND.K.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.2.AND.J.NE.ISLICE) GO TO 10
      IF (IVIEW.EQ.3.AND.I.NE.ISLICE) GO TO 10
      IF(IVIEW.EQ.1) THEN
        X=(XMX(J)+XMN(J))/2.0
        Y=(ZXT(J,I)+ZXB(J,I))/2.0
        DX=XMX(J)-XMN(J)
        DY=ZXT(J,I)-ZXB(J,I)
        CALL SYMBL (X,Y,DX,DY,1)
      ELSE IF(IVIEW.EQ.2) THEN
        IF(IXYDIR.EQ.0) THEN
          II=NROW-I+1
        ELSE
          II=I
        END IF
        X=(YMX(II)+YMN(II))/2.0
        Y=(ZXT(II,K)+ZXB(II,K))/2.0
        CALL GETCPT(II,K,ZXT,ZXB,NROW,NLAY,YP,7)
        XP(1)=YMN(II)
        XP(2)=X
        XP(3)=YMX(II)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      ELSE IF(IVIEW.EQ.3) THEN
        IF(IXYDIR.EQ.0) THEN
          JJ=J
        ELSE
          JJ=NCOL-J+1
        END IF
        X=(XMX(JJ)+XMN(JJ))/2.0
        Y=(ZXT(JJ,K)+ZXB(JJ,K))/2.0
        CALL GETCPT(JJ,K,ZXT,ZXB,NCOL,NLAY,YP,7)
        XP(1)=XMN(JJ)
        XP(2)=X
        XP(3)=XMX(JJ)
        XP(4)=XP(3)
        XP(5)=XP(2)
        XP(6)=XP(1)
        XP(7)=XP(1)
        CALL PLOTPL(7,XP,YP)
      END IF
10    CONTINUE
      END IF
5020   FORMAT(3I10,2F10.0,I10)
      WRITE(I7,*) '  GHB DATA HAS BEEN READ...'
      IF (NCLR.GE.0) CALL PKCLR (ICO(7))
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE SPTR1(IU,I7,KPER)
      CHARACTER*81 LINE
C
C... MAKE FIRST PASS AND FIND OUT WHAT STRESS PERIOD DATA IS BEING USED
C    IN STRESS PERIOD "KPER"
C
      REWIND(IU)
      READ(IU,*)
      DO 10 IPER=1,KPER
      READ(IU,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IU)
C... ITMP CANNOT BE < 0 FOR THE FIRST STRESS PERIOD
      IF(ITMP.LT.0 .AND. IPER.EQ.1) THEN
      WRITE(I7,*) 'ITMP < 0 FOR STRESS PERIOD 1. RUN STOPPED.'
      STOP
      END IF
      IF(ITMP.GE.0) KKPER=IPER
      IF(ITMP.GT.0) THEN
      DO 15 N=1,ITMP
      READ(IU,*)
15    CONTINUE
      END IF
10    CONTINUE
C
C... REWIND FILE AND READ THROUGH IT AGAIN TO GET TO THE BEGINNING OF THE
C    DATA THAT APPLIES FOR PERIOD KPER
      KM1=KKPER-1
      REWIND(IU)
      READ(IU,*)
      IF(KM1.GT.0) THEN
      DO 20 IPER=1,KM1
      READ(IU,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IU)
      IF(ITMP.GT.0) THEN
      DO 25 N=1,ITMP
      READ(IU,'(A)') LINE
25    CONTINUE
      END IF
20    CONTINUE
      END IF
C
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE PSTRM (IMIN,IMAX,JMIN,JMAX,KMIN,KMAX,XMN,XMX,YMN,
     1 YMX,NCOL,NROW,NLAY,IUSTR,NCLR,IVIEW,IBUFF,I7,KPER)
      COMMON /COLORS/
     1 ICO(20),ICYCL(20),CTR(0:255),CTG(0:255),CTB(0:255),NCYCL,NCTDEF,
     2 MCI
      DIMENSION XMN(NCOL),XMX(NCOL),YMX(NROW),YMN(NROW),
     1 IBUFF(NCOL,NROW,NLAY)
      CHARACTER*81 LINE
      CHARACTER*26 STRING
C
      IF(IVIEW.GT.1) RETURN
 
      DO 10 K=1,NLAY
      DO 10 I=1,NROW
      DO 10 J=1,NCOL
10    IBUFF(J,I,K)=0
      IF (NCLR.GE.0) THEN
      CALL PKCLR (ICO(11) )
      END IF
      WRITE(I7,5000)
5000  FORMAT(' ---------------------------------------------------------
     1----------------------')
      WRITE(I7,*) 'STREAM DATA NOW BEING READ...'
      CALL SPTR2(IUSTR,I7,KPER)
      READ(IUSTR,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IUSTR)
      IF(ITMP.EQ.0) GO TO 30
      WRITE(I7,1000) ITMP
1000  FORMAT(1X,I6,' STREAM CELLS WILL BE PROCESSED.')
      DO 20 N=1,ITMP
      READ(IUSTR,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,K,RDUMMY,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,I,RDUMMY,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,J,RDUMMY,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IS,RDUMMY,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IR,RDUMMY,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,F,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,H,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,C,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,E,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,3,NDUMMY,STOP,I7,IUSTR)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,IFACE,RDUMMY,I7,IUSTR)
      ISKIP=0
      IF(I.LT.IMIN.OR.I.GT.IMAX) ISKIP=1
      IF(J.LT.JMIN.OR.J.GT.JMAX) ISKIP=2
      IF(K.LT.KMIN.OR.K.GT.KMAX) ISKIP=3
      IF (IBUFF(J,I,K).EQ.1) ISKIP=4
      IF (IFACE.GT.6) ISKIP=5
      IF(ISKIP.GT.0) GO TO 25
      IBUFF(J,I,K)=1
      II=NROW-I+1
      DX=XMX(J)-XMN(J)
      DY=YMX(II)-YMN(II)
      X= (XMX(J)+XMN(J))/2.0
      Y= (YMX(II)+YMN(II))/2.0
      CALL SYMBL (X,Y,DX,DY,0)
      STRING= '      PLOTTED STREAM REACH'
      GO TO 20
25    CONTINUE
      IF(ISKIP.GE.1 .AND. ISKIP.LE.3) THEN
        STRING= ' STREAM REACH OUTSIDE PLOT'
      ELSE IF(ISKIP.EQ.4) THEN
        STRING= '    DUPLICATE STREAM REACH'
      ELSE IF(ISKIP.EQ.5) THEN
        STRING= 'IFACE > 6 FOR STREAM REACH'
      END IF
20    WRITE(I7,1100) STRING,N,K,I,J
1100  FORMAT(1X,A,I5,' IN: LAYER, ROW, COL = ',3(1X,I4))
30    CONTINUE
      WRITE(I7,*) '  STREAM DATA HAS BEEN READ'
      IF (NCLR.GE.0) CALL PKCLR (ICO(7))
      CLOSE(IUSTR)
      RETURN
      END
 
C***** SUBROUTINE *****
      SUBROUTINE SPTR2(IU,I7,KPER)
      CHARACTER*81 LINE
C
C... MAKE FIRST PASS AND FIND OUT WHAT STRESS PERIOD DATA IS BEING USED
C    IN STRESS PERIOD "KPER"
C
      REWIND(IU)
      READ(IU,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,MXSTRM,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NSS,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NTRIB,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,NDIV,RDUMMY,I7,IU)
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ICALC,RDUMMY,I7,IU)
 
      DO 10 IPER=1,KPER
      READ(IU,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IU)
C... ITMP CANNOT BE < 0 FOR THE FIRST STRESS PERIOD
      IF(ITMP.LT.0 .AND. IPER.EQ.1) THEN
      WRITE(I7,*) 'ITMP < 0 FOR STRESS PERIOD 1. RUN STOPPED.'
      STOP
      END IF
      IF(ITMP.GE.0) KKPER=IPER
 
      IF(ITMP.GT.0) THEN
C... CLEAR LIST OF STREAM REACHES
      DO 15 N=1,ITMP
      READ(IU,'(A)') LINE
15    CONTINUE
C... CLEAR OTHER JUNK IF PRESENT
      IF(ICALC.GT.0) THEN
      DO 30 L=1,ITMP
30    READ(IU,'(A)') LINE
      END IF
      IF(NTRIB.GT.0) THEN
        DO 40 L=1,NSS
40      READ(IU,'(A)') LINE
      END IF
      IF(NDIV.GT.0) THEN
        DO 50 L=1,NSS
50      READ(IU,'(A)') LINE
      END IF
      END IF
 
10    CONTINUE
C
C... REWIND FILE AND READ THROUGH IT AGAIN TO GET TO THE BEGINNING OF THE
C    DATA THAT APPLIES FOR PERIOD KPER
      KM1=KKPER-1
      REWIND(IU)
      READ(IU,*)
      IF(KM1.GT.0) THEN
      DO 20 IPER=1,KM1
      READ(IU,'(A)') LINE
      ICOL=1
      CALL URWORD(LINE,ICOL,IWSTRT,IWLAST,2,ITMP,RDUMMY,I7,IU)
      IF(ITMP.GT.0) THEN
      DO 25 N=1,ITMP
      READ(IU,'(A)') LINE
25    CONTINUE
C... CLEAR OTHER JUNK IF PRESENT
      IF(ICALC.GT.0) THEN
      DO 35 L=1,ITMP
35    READ(IU,'(A)') LINE
      END IF
      IF(NTRIB.GT.0) THEN
        DO 45 L=1,NSS
45      READ(IU,'(A)') LINE
      END IF
      IF(NDIV.GT.0) THEN
        DO 55 L=1,NSS
55      READ(IU,'(A)') LINE
      END IF
      END IF
20    CONTINUE
      END IF
C
      RETURN
      END
